import Head from 'next/head'
import Navbar from '../components/navbar'
import { useEffect, useState } from 'react'

export default function Home() {
  const [navActive, setNavActive] = useState<boolean>(false);
  useEffect(() => {
    window.addEventListener("scroll", (e) => {
      if(Math.floor(scrollY) > 50 && !navActive){
        setNavActive(true);
      } else if(Math.floor(scrollY) == 0) {
        setNavActive(false);
      }
    });
  }, [])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main 
        style={{
          backgroundImage: `url('/background.svg')`,
          backgroundAttachment: 'fixed'
        }}
        className="bg-[#272829] flex flex-col items-center justify-center min-h-[100vh] min-w-[100%] bg-no-repeat bg-cover bg-center ">
          <Navbar isActive={navActive} />
          <div className='h-[60vh] flex flex-col justify-center w-1/2 rounded-xl'>
            <div className="text-container">
              <h1 className='text-5xl text-[#D8D9DA] inline-block'>Hi, I'm </h1>
              <h1 className='inline-block text-5xl font-bold'>&nbsp;</h1>
              <span className='inline-block text-5xl font-bold hue-rotate-15 text-[#D8D9DA]'>Armaan.</span>
            </div>
          </div>
      </main>
    </>
  )
}
